spring:
  profiles:
    active: dev
  application:
    name: mango-oauth2-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    name: mysql
    url: jdbc:mysql://127.0.0.1:3306/mango?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 150
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 9
    host: 127.0.0.1
    port: 6379
    timeout: 600000
    lettuce:
      pool:
        max-active: 1000 #最大连接数 （使用负值表示没有限制）
        max-idle: 1000 #最大空闲连接
        max-wait: -1 #连接的最大等待阻塞的时间 （使用负值表示没有限制）
        min-idle: 0 #最小空闲连接
      shutdown-timeout: 4000 #关闭时的超时时间
    password: YxjRedis
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
